# Generated by Django 3.0.6 on 2020-06-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodilan', '0006_auto_20200601_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TAM ZAMANLI'), (2, 'YARI ZAMANLI'), (3, 'STAJYER'), (4, 'FREELANCE')]),
        ),
    ]
