# Generated by Django 3.0.6 on 2020-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='')),
                ('www', models.URLField()),
                ('twitter', models.CharField(max_length=15)),
                ('linkedin', models.URLField()),
                ('pub_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
