# Generated by Django 3.0.6 on 2020-06-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='activation_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='apply_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='apply_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='renewal_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
